name: "Build"
on:
  workflow_dispatch: {}
  # Build a new image every week
  schedule:
    # Sunday 3:41 AM is a random moment in the week that I expect is the lowest
    # load for GH. No idea if true.
    - cron: '41 3 * * 0'

permissions:
  # To create a new release
  contents: write

jobs:
  digitalocean:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: "Pin the nixpkgs channel to nixos-unstable"
      # Works for the local user only! And this only pins the registry, which is
      # only used by flakes, it just happens that the DeterminateSystems nix
      # installer also sets extra-nix-path = nixpkgs=flake:nixpkgs, which makes
      # nix-build pick up on this, too.
      run: |
        nix registry add nixpkgs github:NixOS/nixpkgs/nixos-unstable
    - name: Build DO image
      run: |
        nix-build digitalocean-image.nix
        cp result/*.qcow2.gz nixos-digitalocean-x86_64-linux.qcow.gz
    - uses: "actions/upload-artifact@v4"
      name: "Upload image artifact"
      with:
        name: "nixos-digitalocean-x86_64-linux-${{ github.sha }}.qcow2.gz"
        path: "nixos-digitalocean-x86_64-linux.qcow.gz"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          nixos-digitalocean-x86_64-linux.qcow.gz
